In [8]:
import numpy as np
def gaussian_kernel(t1, t2, sigma):
    """
    Computes the Gaussian kernel value of two time points t1 and t2.

    Args:
        t1 (int): First time point.
        t2 (int): Second time point.
        sigma (float): Variance parameter of the Gaussian kernel.

    Returns:
        float: Gaussian kernel value of the two time points.
    """
    return np.exp(-np.square(t1 - t2) / (2 * np.square(sigma)))

print(f"Distance 1: {gaussian_kernel(1,2,4)}")
print(f"Distance 2: {gaussian_kernel(1,3,4)}")
print(f"Distance 3: {gaussian_kernel(1,4,4)}")
print(f"Distance 4: {gaussian_kernel(1,5,4)}")

def gaussian_kernel_vectorized(t1, t2, sigma):
    """
    Vectorized computation of the Gaussian kernel value for arrays of time points t1 and t2.

    Args:
        t1 (np.array): Array of first time points of shape (n,).
        t2 (np.array): Array of second time points of shape (n,).
        sigma (float): Variance parameter of the Gaussian kernel.

    Returns:
        np.array: Array of Gaussian kernel values.
    """
    return np.exp(-np.square(t1 - t2) / (2 * np.square(sigma)))

Distance 1: 0.9692332344763441
Distance 2: 0.8824969025845955
Distance 3: 0.7548396019890073
Distance 4: 0.6065306597126334


In [20]:
sample_indices = np.arange(6)

t1, t2 = np.meshgrid(sample_indices, sample_indices, indexing='ij')

print(f"t1: {t1}")
print(f"t2: {t2}")

distance_matrix = np.square(t1 - t2)

print(f"Distance matrix: {distance_matrix}")

kernel_matrix = gaussian_kernel_vectorized(distance_matrix, 0, sigma=4)
np.set_printoptions(precision=2, suppress=True)
print(f"Kernel Matrix: {kernel_matrix}")

t1: [[   0    0    0 ...    0    0    0]
 [   1    1    1 ...    1    1    1]
 [   2    2    2 ...    2    2    2]
 ...
 [4442 4442 4442 ... 4442 4442 4442]
 [4443 4443 4443 ... 4443 4443 4443]
 [4444 4444 4444 ... 4444 4444 4444]]
t2: [[   0    1    2 ... 4442 4443 4444]
 [   0    1    2 ... 4442 4443 4444]
 [   0    1    2 ... 4442 4443 4444]
 ...
 [   0    1    2 ... 4442 4443 4444]
 [   0    1    2 ... 4442 4443 4444]
 [   0    1    2 ... 4442 4443 4444]]
Distance matrix: [[       0        1        4 ... 19731364 19740249 19749136]
 [       1        0        1 ... 19722481 19731364 19740249]
 [       4        1        0 ... 19713600 19722481 19731364]
 ...
 [19731364 19722481 19713600 ...        0        1        4]
 [19740249 19731364 19722481 ...        1        0        1]
 [19749136 19740249 19731364 ...        4        1        0]]
Kernel Matrix: [[1.   0.97 0.61 ... 0.    inf  inf]
 [0.97 1.   0.97 ...  inf 0.    inf]
 [0.61 0.97 1.   ... 0.    inf 0.  ]
 ...
 [0.    inf 0.  

C:\Users\xmoot\AppData\Local\Temp\ipykernel_10256\2167713322.py:33: RuntimeWarning: overflow encountered in exp
  return np.exp(-np.square(t1 - t2) / (2 * np.square(sigma)))
