In [8]:
# Links: https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.data.Data.html#torch_geometric.data.Data
import torch
from torch_geometric.data import Data

In [9]:
# Edges
edge_index = torch.tensor([[0, 1, 1, 2],
                           [1, 0, 2, 1]], dtype=torch.long)

# Node features
x = torch.tensor([[-1], [0], [1]], dtype=torch.float32)

# Edge features
edge_attr = torch.tensor([[1, 2, 3, 4]], dtype=torch.float32)

# Graph Label
y = torch.tensor([0], dtype=torch.long)

# We store each graph in a Data object. This Data object is customizable in its attributes.
data = Data(x=x, edge_index=edge_index, edge_attr=edge_attr, y=y)

In [10]:
# Descriptive data of the Data object
# print((data.to_dict()).keys())
print("Number of nodes:", data.num_nodes)
print("Number of edges:", data.num_edges)
print("Number of node features:", data.num_node_features)
print("Number of edge features:", data.num_edge_features)

Number of nodes: 3
Number of edges: 4
Number of node features: 1
Number of edge features: 4


In [11]:
class PairData(Data):
    def __inc__(self, key, value, *args, **kwargs):
        if key == 'edge_index_1':
            return self.x_1.size(0)
        if key == 'edge_index_2':
            return self.x_2.size(0)
        return super().__inc__(key, value, *args, **kwargs)

In [12]:
# Node features of shape (num_nodes, num_node_features) and type torch.float32
x_1 = torch.tensor([[0, 0, 0],
                    [1, 1, 1],
                    [2, 2, 2],
                    [3, 3, 3]], dtype=torch.float32)
x_2 = torch.tensor([[4, 4, 4],
                    [5, 5, 5],
                    [6, 6, 6]], dtype=torch.float32)

# Edge indices of shape (2, num_edges) and type torch.long
edge_index_1 = torch.tensor([[0, 1, 1, 2, 2, 3],
                             [1, 0, 2, 1, 3, 2]], dtype=torch.long)
edge_index_2 = torch.tensor([[0, 1, 1, 2],
                             [1, 0, 2, 1]], dtype=torch.long)

# Edge features of shape (num_edges, num_edge_features) and type torch.float32
edge_attr_1 = torch.tensor([[0],
                            [1],
                            [2],
                            [3],
                            [4],
                            [5]], dtype=torch.float32)
edge_attr_2 = torch.tensor([[6],
                            [7],
                            [8],
                            [9]], dtype=torch.float32)

# Pair label of shape (1,) and type torch.long
y = torch.tensor([1], dtype=torch.float32)

data = PairData(x_1=x_1, edge_index_1=edge_index_1, edge_attr_1=edge_attr_1,  # Graph 1.
                x_2=x_2, edge_index_2=edge_index_2, edge_attr_2=edge_attr_2,  # Graph 2.
                y=y) #Graph pair label. 

print(data.edge_attr_1)

tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])


In [13]:
# Dataloader for pairs of graphs
from torch_geometric.loader import DataLoader
from torch_geometric.data import Batch

# We will have our list of graphs in the form of Data objects
data_list = [data, data, data]

# Create the dataloader. The follow_batch tells the dataloader which nodes belong to which graph in this 
# giant disconnected graph that the batch creates. We can typically split the data_list into train, val, test and then 
# create individual loaders correspondingly.
train_loader = DataLoader(data_list, batch_size=2, follow_batch=['x_1', 'x_2'])


# We can iterate through batches with the following. Each batch is a data.Batch() object
for batch in train_loader:
    inputs = ((batch.x_1, batch.edge_index_1, batch.edge_attr_1), (batch.x_2, batch.edge_index_2, batch.edge_attr_2))
    graph_1, graph_2 = inputs
    labels = batch.y
    print(batch.x_2)
    print(labels)
    print("Which nodes correspond to which graph:", batch.x_1_batch)
    print("Which nodes correspond to which graph:", batch.x_2_batch)

tensor([[4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.],
        [4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.]])
tensor([1., 1.])
Which nodes correspond to which graph: tensor([0, 0, 0, 0, 1, 1, 1, 1])
Which nodes correspond to which graph: tensor([0, 0, 0, 1, 1, 1])
tensor([[4., 4., 4.],
        [5., 5., 5.],
        [6., 6., 6.]])
tensor([1.])
Which nodes correspond to which graph: tensor([0, 0, 0, 0])
Which nodes correspond to which graph: tensor([0, 0, 0])


In [14]:
# A simple GCN model which only takes in two graphs

import torch
import torch.nn.functional as F
from torch.nn import Sequential, Linear, ReLU
from torch_geometric.nn import GCNConv, global_mean_pool

class GraphClassifier(torch.nn.Module):
    def __init__(self, num_node_features, num_edge_features):
        super(GraphClassifier, self).__init__()

        # Node feature transformation layers
        self.conv1 = GCNConv(num_node_features, 64)
        self.conv2 = GCNConv(64, 128)

        # Edge feature transformation layers
        self.edge_mlp = Sequential(Linear(num_edge_features, 32),
                                   ReLU(),
                                   Linear(32, 64))
        
        # Readout layer
        self.readout = global_mean_pool

        # Classifier
        self.classifier = Linear(128, 1)

    def forward(self, x, edge_index, edge_attr, batch):
        # Update node features
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)

        # Update edge features
        edge_attr = self.edge_mlp(edge_attr)

        # Readout layer to get graph-level representation
        x = self.readout(x, batch)  # <-- Use the batch vector here

        # Classifier to predict the graph label
        x = self.classifier(x)
        x = torch.sigmoid(x)

        return x.squeeze(-1)

In [15]:
from torch_geometric.data import DataLoader

# Initialize model
model = GraphClassifier(num_node_features=3, num_edge_features=1)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.BCELoss()

# Training loop
for epoch in range(1, 100):
    for batch in train_loader:
        optimizer.zero_grad()
        out = model(batch.x_1, batch.edge_index_1, batch.edge_attr_1, batch.x_1_batch)  # Use batch.x_1_batch
        loss = criterion(out, batch.y.float())
        loss.backward()
        optimizer.step()
    print(f'Epoch: {epoch}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.38987159729003906
Epoch: 2, Loss: 0.12004198879003525
Epoch: 3, Loss: 0.018851852044463158
Epoch: 4, Loss: 0.001941955997608602
Epoch: 5, Loss: 0.0001847318490035832
Epoch: 6, Loss: 1.9073668227065355e-05
Epoch: 7, Loss: 2.2649790025752736e-06
Epoch: 8, Loss: 3.576279254957626e-07
Epoch: 9, Loss: 1.1920928955078125e-07
Epoch: 10, Loss: 0.0
Epoch: 11, Loss: 0.0
Epoch: 12, Loss: 0.0
Epoch: 13, Loss: 0.0
Epoch: 14, Loss: 0.0
Epoch: 15, Loss: 0.0
Epoch: 16, Loss: 0.0
Epoch: 17, Loss: 0.0
Epoch: 18, Loss: 0.0
Epoch: 19, Loss: 0.0
Epoch: 20, Loss: 0.0
Epoch: 21, Loss: 0.0
Epoch: 22, Loss: 0.0
Epoch: 23, Loss: 0.0
Epoch: 24, Loss: 0.0
Epoch: 25, Loss: 0.0
Epoch: 26, Loss: 0.0
Epoch: 27, Loss: 0.0
Epoch: 28, Loss: 0.0
Epoch: 29, Loss: 0.0
Epoch: 30, Loss: 0.0
Epoch: 31, Loss: 0.0
Epoch: 32, Loss: 0.0
Epoch: 33, Loss: 0.0
Epoch: 34, Loss: 0.0
Epoch: 35, Loss: 0.0
Epoch: 36, Loss: 0.0
Epoch: 37, Loss: 0.0
Epoch: 38, Loss: 0.0
Epoch: 39, Loss: 0.0
Epoch: 40, Loss: 0.0
Epoch: 41,

In [16]:
# Simple graph pair classifier
class PairGraphClassifier(torch.nn.Module):
    def __init__(self, num_node_features, num_edge_features):
        super(PairGraphClassifier, self).__init__()

        # Node feature transformation layers
        self.conv1 = GCNConv(num_node_features, 64)
        self.conv2 = GCNConv(64, 128)

        # Edge feature transformation layers
        self.edge_mlp = Sequential(Linear(num_edge_features, 32),
                                   ReLU(),
                                   Linear(32, 64))

        # Classifier
        self.classifier = Linear(256, 1)  # 128 features from each graph

    def forward_one(self, x, edge_index, edge_attr, batch):
        x = self.conv1(x, edge_index)
        x = F.relu(x)
        x = self.conv2(x, edge_index)
        x = F.relu(x)

        edge_attr = self.edge_mlp(edge_attr)
        x = global_mean_pool(x, batch)  # Use batch vector for separate pooling
        return x

    def forward(self, x_1, edge_index_1, edge_attr_1, batch_1, x_2, edge_index_2, edge_attr_2, batch_2):
        
        x_1 = self.forward_one(x_1, edge_index_1, edge_attr_1, batch_1)
        x_2 = self.forward_one(x_2, edge_index_2, edge_attr_2, batch_2)

        x = torch.cat([x_1, x_2], dim=1)
        x = self.classifier(x)
        x = torch.sigmoid(x)

        return x.squeeze(-1)

In [17]:
# Initialize model
model = PairGraphClassifier(num_node_features=3, num_edge_features=1)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)
criterion = torch.nn.BCELoss()

# Training loop
for epoch in range(1, 20):
    for batch in train_loader:
        optimizer.zero_grad()
        out = model(batch.x_1, batch.edge_index_1, batch.edge_attr_1, batch.x_1_batch,
                    batch.x_2, batch.edge_index_2, batch.edge_attr_2, batch.x_2_batch)
        loss = criterion(out, batch.y)
        loss.backward()
        optimizer.step()
    print(f'Epoch: {epoch}, Loss: {loss.item()}')
print("We have a graph pair model working!!!")

Epoch: 1, Loss: 0.2603623867034912
Epoch: 2, Loss: 0.015843607485294342
Epoch: 3, Loss: 0.0004814830026589334
Epoch: 4, Loss: 1.3351529560168274e-05
Epoch: 5, Loss: 4.768372718899627e-07
Epoch: 6, Loss: 0.0
Epoch: 7, Loss: 0.0
Epoch: 8, Loss: 0.0
Epoch: 9, Loss: 0.0
Epoch: 10, Loss: 0.0
Epoch: 11, Loss: 0.0
Epoch: 12, Loss: 0.0
Epoch: 13, Loss: 0.0
Epoch: 14, Loss: 0.0
Epoch: 15, Loss: 0.0
Epoch: 16, Loss: 0.0
Epoch: 17, Loss: 0.0
Epoch: 18, Loss: 0.0
Epoch: 19, Loss: 0.0
We have a graph pair model working!!!


In [26]:
from torch_geometric.nn import NNConv, GATConv
from torch import nn

class rp_gnn(nn.Module):
    def __init__(self, num_node_features, num_edge_features, hidden_channels, out_channels):
        super(rp_gnn, self).__init__()
        
        # Define the MLP for NNConv
        self.mlp = nn.Sequential(
            nn.Linear(num_edge_features, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, num_node_features * out_channels)
        )
        
        # Define the NNConv layer
        self.conv1 = NNConv(in_channels = num_node_features, out_channels = hidden_channels, nn = self.mlp)
        
        # Define the GATConv layer
        self.conv2 = GATConv(in_channels = hidden_channels, out_channels = hidden_channels, heads=1, concat=False)

        # Define the global average pooling layer
        self.avgpool = global_mean_pool
        
        # Define the first output layer
        self.fc1 = nn.Linear(hidden_channels, out_channels)
        
        # Define the second output layer for logistic regression
        self.fc2 = nn.Linear(out_channels, 1)
        
    def forward_one(self, x, edge_index, edge_attr, batch):
        # First NNConv layer
        x = F.relu(self.conv1(x, edge_index, edge_attr))
        x = F.relu(x)

        # GATConv layer
        x = self.conv2(x, edge_index)
        x = F.relu(x)

        # Global average pooling
        x = self.avgpool(x, batch) #<-- Use batch vector for separate pooling

        # Fully connected layers
        x = self.fc1(x)
        x = F.relu(x)
        
        return x
    
    def forward(self, x_1, edge_index_1, edge_attr_1, batch_1, x_2, edge_index_2, edge_attr_2, batch_2):

        # Compute the graph embeddings
        x_1 = self.forward_one(x_1, edge_index_1, edge_attr_1, batch_1)
        x_2 = self.forward_one(x_2, edge_index_2, edge_attr_2, batch_2)

        # Apply the contrastive module
        x = torch.abs(x_1 - x_2)

        # Apply logistic regression
        x = self.fc2(x)
        x = torch.sigmoid(x)

        return x

In [27]:
# Test Case
# Initialize the model
num_node_features = 10
num_edge_features = 6
hidden_channels = 20
out_channels = 5

model = rp_gnn(num_node_features, num_edge_features, hidden_channels, out_channels)

# Create synthetic data
# Graph 1
x1 = torch.randn((8, num_node_features))  # 8 nodes with 10 features each
edge_index1 = torch.tensor([[0, 1, 2, 3, 4, 5, 6, 7],
                            [1, 2, 3, 4, 5, 6, 7, 0]], dtype=torch.long)  # 8 edges
edge_attr1 = torch.randn((8, num_edge_features))  # 8 edges with 6 features each

batch1 = torch.tensor([0, 0, 0, 0, 0, 0, 0, 0])  # Nodes belong to the same graph

# Graph 2
x2 = torch.randn((8, num_node_features))  # 8 nodes with 10 features each
edge_index2 = torch.tensor([[0, 1, 2, 3, 4, 5, 6, 7],
                            [1, 2, 3, 4, 5, 6, 7, 0]], dtype=torch.long)  # 8 edges
edge_attr2 = torch.randn((8, num_edge_features))  # 8 edges with 6 features each
batch2 = torch.tensor([0, 0, 0, 0, 0, 0, 0, 0])  # Nodes belong to the same graph

# Forward pass
output = model(x1, edge_index1, edge_attr1, batch1, x2, edge_index2, edge_attr2, batch2)

# Print the output
print(output)


RuntimeError: The size of tensor a (8) must match the size of tensor b (2) at non-singleton dimension 0

In [25]:
# Initialize the extended GNN model
num_node_features = 3
num_edge_features = 1
hidden_channels = 64
out_channels = 32

model = rp_gnn(num_node_features, num_edge_features, hidden_channels, out_channels)

# Training loop
for epoch in range(1, 20):
    for batch in train_loader:
        optimizer.zero_grad()
        out = model(batch.x_1, batch.edge_index_1, batch.edge_attr_1, batch.x_1_batch,
                    batch.x_2, batch.edge_index_2, batch.edge_attr_2, batch.x_2_batch)
        loss = criterion(out, batch.y)
        loss.backward()
        optimizer.step()
    print(f'Epoch: {epoch}, Loss: {loss.item()}')
print("We have a graph pair model working!!!")

RuntimeError: The size of tensor a (12) must match the size of tensor b (6) at non-singleton dimension 0